[package]
name = "prediction-creator"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.22", features = ["derive"] }
console = "0.15.8"
dialoguer = "0.11.0"
reqwest = "0.12.9"
tokio = { version = "1.42.0", features = ["full"] }
twitch_api = { version = "0.7.0-rc.8", features = ["reqwest", "helix", "tracing"] }
